version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_USER: swipper_test
      MYSQL_PASSWORD: swipper_test
      MYSQL_ROOT_PASSWORD: swipper_test
      MYSQL_DATABASE: community_post
      TZ: Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - order_net

  backend:
    build: .
    restart: always
    links:
      - db
    ports:
      - 3000:3000
    networks:
      - order_net
    depends_on:
      - db
    command: sh -c "npm run start:dev"

    volumes:
      - backend_data:/community_post

volumes:
  mysql_data:
  backend_data:


networks:
  order_net:
    driver: bridge
